--disallow connections to the replica if it's secondary
USE [master]
ALTER AVAILABILITY GROUP [AOAGName] MODIFY REPLICA ON N'instance name' WITH (SECONDARY_ROLE(ALLOW_CONNECTION = ALL));
ALTER AVAILABILITY GROUP [AOAGName] MODIFY REPLICA ON N'instance name2' WITH (SECONDARY_ROLE(ALLOW_CONNECTION = ALL));
 
--allow connections to the replica if it's secondary
USE [master]
ALTER AVAILABILITY GROUP [AOAGName] MODIFY REPLICA ON N'instance name' WITH (SECONDARY_ROLE(ALLOW_CONNECTION = NO));
ALTER AVAILABILITY GROUP [AOAGName] MODIFY REPLICA ON N'instance name2' WITH (SECONDARY_ROLE(ALLOW_CONNECTION = NO));
