USE [master];
GO
--Create DMK
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'PasswordHere';
GO
--Create a certificate
CREATE CERTIFICATE Cert_Enc WITH SUBJECT = 'CertSubject';
GO
 
USE DBWithTDE;
GO
--Encrypt a database with TDE
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_256
	ENCRYPTION BY SERVER CERTIFICATE Cert_Enc;
GO
ALTER DATABASE DBWithTDE SET ENCRYPTION ON;
GO
--Disable TDE encryption on the database
ALTER DATABASE DBWithTDE SET ENCRYPTION OFF;
GO
